import type { NextPage } from 'next';
import { Head } from '../../components/NextComponents';
import { WrapHeader, WrapFooter } from '../../components/WrapTemplate';
import {
  SectionContainer,
} from './_document';
import { useRouter } from 'next/router';

const Posts: NextPage = () => {
  const router = useRouter()
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>Works | 作品</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapHeader />
      <SectionContainer>
        <h1>{id}</h1>
      </SectionContainer>
      <WrapFooter />
    </>
  );
};

export default Posts;