import type { NextPage } from 'next';
import { Head } from '../../components/NextComponents';
import { WrapHeader, WrapFooter } from '../../components/WrapTemplate';
import { SectionContainer } from './_document';

const Works: NextPage = () => {
  return (
    <>
      <Head>
        <title>Works | 作品回顧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapHeader />
      <SectionContainer>作品</SectionContainer>
      <WrapFooter />
    </>
  );
};

export default Works;