import type { NextPage } from 'next';
import { Head } from '../../components/NextComponents';
import { WrapHeader, WrapFooter } from '../../components/WrapTemplate';
import {
  SectionContainer,
  ListContainer,
  ItemContainer,
  ItemContent,
  ItemPhotos,
  WorkDataType,
  demoData
} from './_document';
// import { faSearch } from '@fortawesome/free-solid-svg-icons';
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const Works: NextPage = () => {
  return (
    <>
      <Head>
        <title>Works | 作品回顧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapHeader />
      <SectionContainer>
        <ListContainer>
          {
            demoData.map((item: WorkDataType) => (
              <ItemContainer key={item.title}>
                <ItemPhotos href={item.url} target="_blank" style={{ backgroundImage: `url(${item.imageUrl})`, position: "relative", width: "100%", height: "0px", paddingBottom: "70%" }}>
                  {/* <ExpandButton>
                    <FontAwesomeIcon icon={faSearch} />
                  </ExpandButton> */}
                </ItemPhotos>
                <ItemContent>
                  <h3 style={{margin: '0'}}>{item.title}</h3>
                </ItemContent>
              </ItemContainer>
            ))
          }
        </ListContainer>
      </SectionContainer>
      <WrapFooter />
    </>
  );
};

export default Works;