import { Head } from "../../components/NextComponents";
import { routeList } from "./_utils";
import ErrorPage from "next/error";

type Props = {
  path: string;
};

type Params = {
  params: {
    path: string;
  };
};

const PathPage = ({ path }: Props) => {
  if (!routeList[path]) return <ErrorPage statusCode={404} />;
  return (
    <>
      <Head>
        <title>{routeList[path].title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{routeList[path].title}</h1>
    </>
  );
};

export async function getStaticProps({ params }: Params) {
  return {
    props: {
      path: params.path,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      {
        params: {
          path: "index",
        },
      },
    ],
    fallback: false,
  };
}

export default PathPage;
