import type { NextPage } from 'next';
import { Head, Image } from '../../components/NextComponents';

import { WrapHeader, WrapFooter } from '../../components/WrapTemplate';
import { SectionContainer } from './_document';


const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About | 關於我</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <WrapHeader />
      <SectionContainer>自我介紹</SectionContainer>
      <SectionContainer>經歷年表</SectionContainer>
      <SectionContainer>技能樹</SectionContainer>
      <WrapFooter />
    </>
  );
}

export default About;
