import type { NextPage } from "next";
import { Head, Image } from "../components/NextComponents";
import styles from "../styles/Home.module.css";

import { WrapHeader, WrapFooter } from "../components/WrapTemplate";
import {
  demoData,
  SectionContainer,
  KvSection,
  ListContainer,
  ItemContainer,
  WorkDataType,
  ItemPhotos,
} from "./_document";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
          rel="stylesheet"
        />
      </Head>
      <WrapHeader />
      <SectionContainer>
        <KvSection>
          <h1>
            HELLO.
            <br /> I&#39;M <span>FULL-STACK</span>
            <br />
            DEVELOPER
          </h1>
        </KvSection>
      </SectionContainer>
      <SectionContainer>
        <ListContainer>
          {demoData.map((item: WorkDataType) => (
            <ItemContainer key={item.title}>
              <ItemPhotos
                href={item.url}
                target="_blank"
                style={{
                  backgroundImage: `url(${item.imageUrl})`,
                  position: "relative",
                  width: "100%",
                  height: "0px",
                  paddingBottom: "70%",
                }}
              ></ItemPhotos>
            </ItemContainer>
          ))}
        </ListContainer>
      </SectionContainer>
      <WrapFooter />
    </>
  );
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>HOME</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     {/* <main className={styles.main}>
  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.tsx</code>
  //       </p>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer> */}
  //   </div>
  // )
};

export default Home;
