import type { NextPage } from 'next';
import { Head, Image } from '../components/NextComponents';

import { WrapHeader, WrapFooter } from '../components/WrapTemplate';
import { SectionContainer } from './_document';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapHeader />
      <SectionContainer>主視覺</SectionContainer>
      <SectionContainer>精選作品回顧</SectionContainer>
      <WrapFooter />
    </>
  );
}

export default Home
